server.port=8088
spring.application.name=reclamations-service

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/livraison_reclamations

# Logs
logging.level.org.springframework.data.mongodb.core=INFO