server.port=8090
spring.application.name=audit-service

# MongoDB - Base unique pour BFExpress
spring.data.mongodb.uri=mongodb://localhost:27017/bfexpress
spring.data.mongodb.auto-index-creation=true

logging.level.org.springframework.data.mongodb.core=INFO
