server.port=8091
spring.application.name=audit-service

# MongoDB Atlas - Base de données cloud pour BFExpress
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.auto-index-creation=true

logging.level.org.springframework.data.mongodb.core=INFO
