server.port=8083
spring.application.name=tracking-service

# MongoDB (Option A: base de donnees dediee livraison_tracking)
spring.data.mongodb.uri=mongodb://localhost:27017/livraison_tracking

# Logs
logging.level.org.springframework.data.mongodb.core=INFO
