server.port=8089
spring.application.name=stats-service

# MongoDB - Base unique pour BFExpress
spring.data.mongodb.uri=mongodb://localhost:27017/bfexpress
spring.data.mongodb.auto-index-creation=true

# Logs
logging.level.org.springframework.data.mongodb.core=INFO