server.port=8086
spring.application.name=notifications-service

# MongoDB (Option A: base de donnees dediee livraison_notifications)
spring.data.mongodb.uri=mongodb://localhost:27017/livraison_notifications

# Logs
logging.level.org.springframework.data.mongodb.core=INFO
