server.port=8086
spring.application.name=vehicles-service

# MongoDB Atlas - Base de données cloud pour BFExpress
spring.data.mongodb.uri=mongodb+srv://donia:jCn8Pt1ZhyF5ewRy@timsoftstage.192tpcj.mongodb.net/bfexpress?retryWrites=true&w=majority
spring.data.mongodb.auto-index-creation=true

# Logs
logging.level.org.springframework.data.mongodb.core=INFO