server.port=8086
spring.application.name=vehicles-service

# MongoDB Atlas - Base de données cloud pour BFExpress
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.auto-index-creation=true

# Logs
logging.level.org.springframework.data.mongodb.core=INFO