server.port=8085
spring.application.name=ia-service

# MongoDB Atlas - Base de données cloud pour BFExpress
spring.data.mongodb.uri=mongodb+srv://donia:jCn8Pt1ZhyF5ewRy@timsoftstage.192tpcj.mongodb.net/bfexpress?retryWrites=true&w=majority
spring.data.mongodb.auto-index-creation=true

# Logs
logging.level.org.springframework.data.mongodb.core=INFO

# Python AI Service integration URL
ia.python.url=http://localhost:5000

# Utiliser le service Machine Learning (Random Forest) au lieu de K-Means
ia.use.ml=true
