server.port=8085
spring.application.name=ia-service

# MongoDB (Option A: base de donnees dediee livraison_ia)
spring.data.mongodb.uri=mongodb://localhost:27017/livraison_ia

# Logs
logging.level.org.springframework.data.mongodb.core=INFO

# Python AI Service integration URL
ia.python.url=http://localhost:5000/api/ia
