server.port=8084
spring.application.name=livreurs-service

# MongoDB (Option A: base de donnees dediee livraison_livreurs)
spring.data.mongodb.uri=mongodb://localhost:27017/livraison_livreurs

# Logs
logging.level.org.springframework.data.mongodb.core=INFO
