server.port=8084
spring.application.name=livreurs-service

# MongoDB Atlas - via variable d'environnement
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.auto-index-creation=true

# Audit service
audit.service.url=${AUDIT_SERVICE_URL:http://localhost:8090}

# Logs
logging.level.org.springframework.data.mongodb.core=INFO