server.port=8084
spring.application.name=livreurs-service

# MongoDB - Base unique pour BFExpress
spring.data.mongodb.uri=mongodb://localhost:27017/bfexpress
spring.data.mongodb.auto-index-creation=true

# Audit service
audit.service.url=http://localhost:8090

# Logs
logging.level.org.springframework.data.mongodb.core=INFO
