server.port=8081
spring.application.name=commandes-service

# MongoDB Community - Base de données locale gratuite
spring.data.mongodb.uri=mongodb://localhost:27017/bfexpress
spring.data.mongodb.auto-index-creation=true

# Audit service
audit.service.url=http://localhost:8090

# Logs en dev
logging.level.org.springframework.data.mongodb.core=INFO