server.port=8081
spring.application.name=commandes-service

# MongoDB (Option A: base de donnees dediee livraison_commandes)
spring.data.mongodb.uri=mongodb://localhost:27017/livraison_commandes

# Logs en dev
logging.level.org.springframework.data.mongodb.core=INFO